### Get All Decades
GET {{Api_HostAddress}}/api/v1/decades/
Accept: application/json

### Get Decade 2010
GET {{Api_HostAddress}}/api/v1/decades/2010/
Accept: application/json

### Get Issue 1
GET {{Api_HostAddress}}/api/v1/issues/1/
Accept: application/json

### Get Page 1
GET {{Api_HostAddress}}/api/v1/pages/1/
Accept: application/json

### Get Page 2
GET {{Api_HostAddress}}/api/v1/pages/2/
Accept: application/json
